routes/web.php
<?php

// Localisation:
Route::group(['prefix' => LaravelLocalization::setLocale(), 'middleware' => ['localeSessionRedirect', 'localizationRedirect']], function () {

    // Front:
    Route::group(['namespace' => 'Front'], function () {

        // Main:
        Route::get('/', 'FrontController@index')->name('root');
        Route::get('/404-page-not-found', 'FrontController@show404')->name('show404');
        Route::get('/warranty', 'FrontController@warranty')->name('warranty');
        Route::get('/delivery', 'FrontController@delivery')->name('delivery');
        Route::get('/about-us', 'FrontController@about_us')->name('about-us');
        Route::get('/contacts', 'FrontController@contacts')->name('contacts');

        // Catalogue:
        Route::group(['prefix' => 'catalogue'], function () {
            Route::get('/', 'CatalogueController@index')->name('catalogue');
            Route::post('/', 'CatalogueController@ajaxCatalogue')->name('catalogue.ajax');
            Route::get('/product/{id}', 'CatalogueController@product')->name('catalogue.product');
            Route::post('/product/preview', 'CatalogueController@ajaxPreviewProduct')->name('catalogue.product.preview.ajax');
        });

        // Account:
        Route::group(['prefix' => 'account', 'middleware' => 'role:superadministrator|administrator|editor|user', 'middleware_handling' => 'redirect'], function () {

            // Main:
            Route::get('/', 'AccountController@index')->name('account');
            Route::get('/edit', 'AccountController@editAccount')->name('account.edit');
            Route::post('/update', 'AccountController@updateAccount')->name('account.update');

            // Cart:
            Route::get('/cart', 'CartController@index')->name('account.cart');
            Route::post('/cart/quantity', 'CartController@ajaxQuantity')->name('account.cart.quantity.ajax');
            Route::post('/cart/add', 'CartController@add')->name('account.cart.add');
            Route::post('/cart/remove', 'CartController@remove')->name('account.cart.remove');

            // Wishlist:
            Route::get('/wishlist', 'WishlistController@index')->name('account.wishlist');
            Route::post('/wishlist/change', 'WishlistController@change')->name('account.wishlist.change');

            // Review:
            Route::post('/review/publish', 'ReviewController@publish')->name('account.review.publish');

            // Order:
            Route::get('/orders', 'OrderController@index')->name('account.orders');
            Route::get('/orders/{id}', 'OrderController@order')->name('account.order');
            Route::post('/order/cancel', 'OrderController@cancelOrder')->name('account.order.cancel');
            Route::post('/order/complete', 'OrderController@completeOrder')->name('account.order.complete');
            Route::get('/order/checkout', 'OrderController@checkoutOrder')->name('account.order.checkout');
            Route::get('/order/invoice/download/{id}', 'OrderController@downloadInvoice')->name('account.order.invoice.download');
            Route::post('/order/notes', 'OrderController@ajaxOrderNotes')->name('account.order.notes.ajax');
            Route::post('/order/notes/update', 'OrderController@updateOrderNotes')->name('account.order.notes.update');
        });

    });

    // Admin:
    Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => 'role:superadministrator|administrator|editor', 'middleware_handling' => 'redirect', 'middleware_params' => '/home',], function () {

        // Main:
        Route::get('/', 'AdminController@index')->name('admin');
        Route::get('/system/info', 'AdminController@info')->name('system.info');
        Route::get('/system/logs', 'AdminController@logs')->name('system.logs');

        // User:
        Route::resource('/users', 'UserController');
        Route::resource('/permissions', 'PermissionController');
        Route::resource('/roles', 'RoleController');

        // Product:
        Route::resource('/products', 'ProductController');
        Route::post('/products/visible', 'ProductController@productVisibleChange')->name('product.visible');
        Route::post('/products/quantity', 'ProductController@productQuantityChange')->name('product.quantity');

        // Review:
        Route::resource('/reviews', 'ReviewController');
        Route::post('/reviews/visible', 'ReviewController@reviewVisibleChange')->name('review.visible');

        // Order:
        Route::resource('/orders', 'OrderController');
        Route::post('/orders', 'OrderController@changeOrderStatus')->name('order.status.ajax');
        Route::post('/orders/update/tracking-number', 'OrderController@updateTrackingNumber')->name('order.tracking.number.update');
        Route::post('/order/viewed', 'OrderController@orderViewed')->name('order.viewed');

        // Extra:
        Route::resource('/categories', 'CategoryController');
        Route::resource('/subcategories', 'SubcategoryController');
        Route::resource('/materials', 'MaterialController');
        Route::resource('/styles', 'StyleController');
        Route::resource('/tags', 'TagController');
        Route::resource('/sets', 'SetController');
        Route::resource('/sizes', 'SizeController');
        Route::resource('/colors', 'ColorController');
        Route::resource('/gems', 'GemController');
        Route::resource('/photos', 'PhotoController');
        Route::resource('/customers', 'CustomerController');
        Route::resource('/statuses', 'StatusController');
    });

    // Authentication:
    Auth::routes();
    Route::get('/logout', 'Auth\LoginController@logout')->name('logout');
});

app/Http/Controllers/Front/AccountController.php
<?php

namespace App\Http\Controllers\Front;

use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;
use App\Address;

class AccountController extends Controller
{
    public function index()
    {
        $user = Auth::user();
        $orders_amount = $user->orders()->count();
        $wishlist_amount = $user->wishlists()->count();
        $cart_amount = $user->carts()->count();

        return view('front.account.dashboard', compact('orders_amount', 'wishlist_amount', 'cart_amount'));
    }

    public function editAccount()
    {
        $user = Auth::user();
        $delivery_address = $user->address()->first();
        return view('front.account.edit', compact('user', 'delivery_address'));
    }

    public function updateAccount(Request $request)
    {

        $user = Auth::user();

        $this->validate($request, [
            'first_name' => 'required|max:100',
            'last_name' => 'required|max:100',
            'email' => 'required|max:100|unique:users,email,' . $user->id,
            'phone_number' => 'required|max:100',
            'company_name' => 'nullable|max:100',
            'dob' => 'nullable|max:100',
            'address_line' => 'required|max:255',
            'city' => 'required|max:255',
            'state' => 'required|max:255',
            'country' => 'required|max:255',
            'zip' => 'required|max:10'
        ]);

        // Update user:
        $user->first_name = $request->first_name;
        $user->last_name = $request->last_name;
        $user->email = $request->email;
        $user->phone_number = $request->phone_number;
        $user->dob = $request->dob;
        $user->company_name = $request->company_name;

        if ($request->password && $request->password == $request->confirm_password) {
            $user->password = bcrypt($request->password);
        }

        $user->save();

        // Update delivery address:

        $delivery_address = $user->address()->first();

        if (!$delivery_address) {
            $delivery_address = new Address();
            $delivery_address->user_id = $user->id;
        }

        $delivery_address->city = $request->city;
        $delivery_address->state = $request->state;
        $delivery_address->country = $request->country;
        $delivery_address->zip = $request->zip;
        $delivery_address->address_line = $request->address_line;
        $delivery_address->save();

        $message = 'Account Updated';
        session()->flash('notification', $message);
        return redirect(route('account'));
    }
}

app/Http/Controllers/Front/CartController.php
<?php

namespace App\Http\Controllers\Front;

use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;
use App\Product;

class CartController extends Controller
{
    public function index()
    {
        $user = Auth::user();
        $cart_subtotal = 0;
        $cart_amount = 0;
        $cart_products = $user->carts()->get()->keyBy('id');

        foreach ($cart_products as $cart_product) {

            // Check if product is in stock and visible:
            if ($cart_product->quantity < $cart_product->pivot->quantity || !$cart_product->is_visible) {
                Auth::user()->carts()->detach($cart_product);
            } else {
                $cart_subtotal += (($cart_product->getDiscountPrice()) ? $cart_product->getDiscountPrice() : $cart_product->price) * $cart_product->pivot->quantity;
                $cart_amount += $cart_product->pivot->quantity;
            }
        }

        $cart_products = $user->carts()->paginate(10);
        return view('front.account.cart', compact('user', 'cart_products', 'cart_amount', 'cart_subtotal'));
    }

    public function add(Request $request)
    {
        $this->validate($request, [
            'size' => 'numbers|nullable',
            'quantity' => 'integer|min:1',
            'product_id' => 'integer|min:1',
        ]);

        $product = Product::findOrFail($request->product_id);

        if ($product->sizes()->count() > 0 && $request->size || $product->sizes()->count() == 0 && !$request->size) {
            $size = $request->size ? $request->size : 0;
            $quantity = $request->quantity;
            $discount_price = ($product->getDiscountPrice()) ? $product->getDiscountPrice() : 0;
            $carts = Auth::user()->carts();

            if (!($quantity > $product->quantity)) {

                // Remove duplicate:
                if (Auth::user()->carts->contains($product->id)) {
                    $carts->detach($product->id);
                }
                $carts->attach($product, ['size' => $size, 'quantity' => $quantity, 'discount_price' => $discount_price]);
                return redirect()->route('account.cart');
            }else{
                $message = 'Quantity Exceeded';
            }
        } else {
            $message = 'Size not Selected';
        }
        session()->flash('notification', $message);
        return redirect()->back();
    }

    public function remove(Request $request)
    {
        $this->validate($request, [
            'product_id' => 'integer|min:1'
        ]);

        $product = Product::findOrFail($request->product_id);
        Auth::user()->carts()->detach($product);

        $message = 'Cart Updated';
        session()->flash('notification', $message);
        return redirect()->back();
    }

    public function ajaxQuantity(Request $request)
    {
        if ($request->ajax() && Auth::check()) {

            $this->validate($request, [
                'product_id' => 'numbers',
                'quantity' => 'numbers',
            ]);

            $product = Product::findOrFail($request->product_id);
            $quantity = $request->quantity;
            $old_size = Auth::user()->carts()->where('product_id', $product->id)->first()->pivot->size;
            $discount_price = ($product->getDiscountPrice()) ? $product->getDiscountPrice() : 0;
            $carts = Auth::user()->carts();

            // Remove old, replace by new state:
            if (Auth::user()->carts->contains($product->id) && !($quantity > $product->quantity)) {
                $carts->detach($product->id);

                // Attach new state:
                if ($quantity > 0) {
                    $carts->attach($product, ['size' => $old_size, 'quantity' => $quantity, 'discount_price' => $discount_price]);
                }

                $message = 'Cart Updated';

            } else {
                $message = 'Quantity Exceeded';
            }

            session()->flash('notification', $message);

        } else {
            return 'error';
        }
    }
}

app/Http/Controllers/Front/FrontController.php
<?php

namespace App\Http\Controllers\Front;

use Mcamara\LaravelLocalization\Facades\LaravelLocalization;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Product;

class FrontController extends Controller
{
    private $products_per_page = 15;

    public function index()
    {
        $new_products = Product::where([['is_visible', '=', '1']])->orderBy('created_at', 'desc')->limit(12)->get();
        $discount_offer_product = Product::where([['is_visible', '=', '1'], ['discount_end_date', '>=', date('Y-m-d')]])->orderBy('discount_rate', 'desc')->first();
        $featured_products = Product::where([['is_visible', '=', '1'], ['is_featured', '=', '1']])->orderBy('created_at', 'desc')->limit(4)->get();

        return view('front.home', compact('new_products', 'discount_offer_product', 'featured_products'));
    }

    public function warranty()
    {
        return view('front.info.warranty');
    }

    public function delivery()
    {
        return view('front.info.delivery');
    }

    public function about_us()
    {
        return view('front.info.about_us');
    }

    public function contacts()
    {
        return view('front.info.contacts');
    }

    public function show404()
    {
        return view('errors.404');
    }
}

app/Http/Controllers/Front/ReviewController.php
<?php

namespace App\Http\Controllers\Front;

use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;
use App\Review;

class ReviewController extends Controller
{
    public function publish(Request $request)
    {
        $this->validate($request, [
            'g-recaptcha-response' => 'required|recaptcha',
            'review' => 'required|max:500',
            'score' => 'required|numbers',
            'product_id' => 'required|numbers'
        ]);

        $user = Auth::user();
        $review = new Review();
        $review->user_id = $user->id;
        $review->product_id = $request->product_id;
        $review->body = $request->review;
        $review->score = $request->score;
        $review->save();

        $message = 'Review Published';
        session()->flash('notification', $message);
        return redirect()->back();
    }
}

app/Http/Controllers/Front/WishlistController.php
<?php

namespace App\Http\Controllers\Front;

use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Product;

class WishlistController extends Controller
{
    public function index()
    {
        $wishlist_products = Auth::user()->wishlists()->where('is_visible', '1')->paginate(10);
        return view('front.account.wishlist', compact('wishlist_products'));
    }

    public function change(Request $request)
    {
        $this->validate($request, [
            'product_id' => 'integer|min:1'
        ]);

        $product = Product::findOrFail($request->product_id);
        $wishlists = Auth::user()->wishlists();
        if (Auth::user()->wishlists->contains($product->id)) {
            $wishlists->detach($product->id);
        } else {
            $wishlists->attach($product->id);
        }
        $message = 'Wishlist Updated';
        session()->flash('notification', $message);
        return redirect()->back();
    }
}

resources/views/partials/front/_cart_preview.blade.php
<div class="product-images">
    <div class="main-image images">
        <img class="loading" src="{{$cart_product->photos()->count() > 0 ? $cart_product->photos->first()->getPhotoPath() : '' }}">
    </div>
</div><!-- .product-images -->

{!! Form::open(['method'=>'POST','route'=>'account.cart.add','class'=>'form-horizontal']) !!}

<div class="product-info">
    <h1>{{$cart_product->name}} ({{$cart_product->code}})</h1>
    <div class="price-box-3">
        <div class="s-price-box">
            @if($cart_product->getDiscountPrice())
                <span class="new-price">&euro; {{$cart_product->getDiscountPrice()}}</span>
                <span class="old-price">&euro; {{$cart_product->price}}</span>
            @else
                <span class="new-price">&euro; {{$cart_product->price}}</span>
            @endif
        </div>
    </div>
    <input type="hidden" name="product_id" value="{{$cart_product->id}}">
    @if($sizes->count() > 0)
        <div class="single-pro-color-rating sizes-border clearfix">
            <div class="sin-pro-color">
                <p class="color-title f-left" style="font-weight: 600;margin-right: 12px">{{trans('front/cart.sizes')}}: </p>
                <div class="sizes-list f-left">
                    <ul>
                        @foreach($sizes as $size)
                            <li>
                                <input type="radio" name="size" id="size_{{$size->id}}" value="{{$size->value}}"/>
                                <label for="size_{{$size->id}}"><span>{{ ( ($size->value < 10)||(strlen(strval($size->value))) < 3 )  ? '&nbsp;'.$size->value : $size->value}}</span></label>
                            </li>
                        @endforeach
                    </ul>
                </div>
            </div>
        </div>
    @endif
    <div class="row s-price-box" style="margin: 0;padding: 15px 0;border-top: none;    border-bottom: 1px solid #e5e5e5;">
        <div class="col-md-6" style="padding-left: 0">
            <div class="sin-pro-color f-left">
                <p class="color-title f-left" style="margin-bottom: 0px;margin-top: 2px;">{{trans('front/cart.material')}}:</p>
                <div class="f-left" style="font-size: 16px;margin-top: 2px">
                    &nbsp;&nbsp;&nbsp;{{$cart_product->material->name}}
                </div>
            </div>
        </div>
        <div class="col-md-6" style="padding-right: 0">
            @if($cart_product->gems->count() > 0)
                <div class="f-right" style="margin-right: 15px;margin-top: -3px">
                    <p class="color-title f-left" style="margin-top: 4px;margin-bottom: 0px">{{trans('front/cart.gems')}}: </p>
                    <div class="f-left">
                        <ul class="product-gem" style="    margin-bottom: -4px;">
                            @foreach($cart_product->gems->take(3) as $gem)
                                <img src="{{$gem->image}}" alt="{{$gem->name}}" class="img-thumbnail tippy-gem" title="{{$gem->name}}" style="margin-bottom: 0px;height: 35px; width: 35px;">
                            @endforeach
                        </ul>
                    </div>
                </div>
            @endif
        </div>
    </div>
    <div class="row s-price-box" style="margin: 0;padding: 15px 0;border-top: none;    border-bottom: 1px solid #e5e5e5;">
        <div class="col-md-6" style="padding-left: 0">
            <div class="sin-pro-color f-left">
                <p class="color-title f-left" style="margin-bottom: 0px;margin-top: 2px;">{{trans('front/cart.weight')}}: </p>
                <div class="f-left" style="font-size: 16px;margin-top: 2px">
                    &nbsp;&nbsp;&nbsp;{{$cart_product->weight}} {{trans('front/cart.grams')}}
                </div>
            </div>
        </div>
        <div class="col-md-6" style="padding-right: 0">

        </div>
    </div>
    <div class="quick-add-to-cart" style="margin-bottom: -15px; margin-top: 20px;">
        <div class="numbers-row">
            <input type="number" name="quantity" id="french-hens" value="1" min="0" max="{{$cart_product->quantity}}">
        </div>
        <button class="single_add_to_cart_button" type="submit">{{trans('front/cart.add_to_cart')}}</button>
    </div>
</div><!-- .product-info -->

{!! Form::close() !!}

resources/views/partials/front/_product_catalogue.blade.php
<div class="tab-content">

@if($products && $products->count() > 0)
    @if(request('view')=='list')
        <!-- list-view -->
            <div>
                <div class="row">
                    <!-- product-item start -->
                    @foreach($products as $product)
                        <div class="col-md-12">
                            <div class="shop-list product-item">
                                <div class="product-img">
                                    <a href="{{route('catalogue.product',$product->id)}}">
                                        @if($product->photos->count() > 0)
                                            <img class="loading" src="{{$product->photos->first()->getPreviewPath()}}" style="width: 100%;height: 28rem" alt="">
                                        @else
                                            <img class="loading" src="{{asset('img/product/7.jpg')}}" style="width: 100% ; height: 28rem" alt=""/>
                                        @endif
                                    </a>
                                </div>
                                <div class="product-info">
                                    <div class="clearfix">
                                        <h6 class="product-title f-left">
                                            <a style="font-size: 18px" href="{{route('catalogue.product',$product->id)}}">{{$product->name}} &nbsp;&nbsp;&nbsp;&nbsp;</a>
                                        </h6>
                                    </div>
                                    <h6 class="brand-name mb-20" style="font-size: 18px; color: #1a237e;font-style: normal;">{{$product->code}}</h6>
                                    <div class="row s-price-box" style="margin: 0;padding: 15px 0">
                                        <div class="col-md-6" style="padding-left: 0">
                                            <div class="sin-pro-color f-left">
                                                <p class="color-title f-left" style="margin-bottom: 0px;margin-top: 2px;">Material: </p>
                                                <div class="f-left" style="font-size: 16px;margin-top: 2px">
                                                    &nbsp;&nbsp;&nbsp;{{$product->material->name}}
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-6" style="padding-right: 0">
                                            @if($product->gems->count() > 0)
                                                <div class="f-right" style="margin-right: 15px;margin-top: -3px">
                                                    <p class="color-title f-left" style="margin-top: 4px;margin-bottom: 0px">Gem: </p>
                                                    <div class="f-left">
                                                        <ul class="product-gem" style="    margin-bottom: -4px;">
                                                            @foreach($product->gems->take(3) as $gem)
                                                                <img src="{{$gem->image}}" alt="{{$gem->name}}" class="img-thumbnail tippy-gem" title="{{$gem->name}}" style="margin-bottom: 0px;height: 35px; width: 35px;">
                                                            @endforeach
                                                        </ul>
                                                    </div>
                                                </div>
                                            @endif
                                        </div>
                                    </div>

                                    <div class="s-price-box mb-15">
                                        @if($product->getDiscountPrice())
                                            <span class="new-price">&euro; {{number_format ($product->getDiscountPrice(),2)}}</span>
                                            <span class="old-price">&euro; {{number_format ($product->price,2)}}</span>
                                            <span class="discount_list_view">- {{$product->discount_rate}} %</span>
                                        @else
                                            <span class="new-price">&euro; {{number_format ($product->price,2)}}</span>
                                        @endif
                                    </div>

                                    <ul class="action-button clearfix">
                                        <li>
                                            {!! Form::open(['method'=>'POST','route'=>['account.wishlist.change']]) !!}
                                            <input type="hidden" name="product_id" value="{{$product->id}}">
                                            <button class="cart_wishlist {{(Auth::check() && Auth::user()->wishlists->contains($product->id))?'active':''}} tippy" title="{{trans('front/products.add_to_wishlist')}}" data-product="{{$product->id}}">
                                                <i class="zmdi zmdi-favorite"></i>
                                            </button>
                                            {!! Form::close() !!}
                                        </li>
                                        <li>
                                            <a class="cart_product tippy" data-toggle="modal" data-target="#productModal" title="{{trans('front/products.add_to_cart')}}" data-product="{{$product->id}}"><i class="zmdi zmdi-shopping-cart-plus"></i></a>
                                        </li>
                                        @if(Auth::check())
                                            @role('superadministrator|administrator|editor')
                                            <li>
                                                <a class="cart_product tippy" title="{{trans('front/products.edit_product')}}" href="{{route('products.edit',$product->id)}}"><i class="zmdi zmdi-edit"></i></a>
                                            </li>
                                            @endrole
                                        @endif
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <!-- product-item end -->
                    @endforeach
                </div>
            </div>
    @else
        <!-- grid-view -->
            <div>
                <div class="row">
                @foreach($products as $product)
                    <!-- product-item start -->
                        <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                            <div class="product-item {{($product->getDiscountPrice())?'product-item-discount':''}}">
                                @if($product->getDiscountPrice())
                                    <div class="ribbon-price">
                                        <span>-&nbsp;{{$product->discount_rate < 10?'&nbsp;':''}}{{$product->discount_rate}}%</span>
                                    </div>
                                @endif
                                <div class="product-img">
                                    <a href="{{route('catalogue.product',$product->id)}}">
                                        @if($product->photos->count() > 0)
                                            <img class="loading" src="{{$product->photos->first()->getPreviewPath()}}" alt="">
                                        @else
                                            <img class="loading" src="{{asset('img/product/7.jpg')}}" style="width: 100% ; height: 28rem" alt=""/>
                                        @endif
                                    </a>
                                </div>
                                <div class="product-info">
                                    <h6 class="product-title" style="font-size: 18px">
                                        <a href="{{route('catalogue.product',$product->id)}}">{{$product->name}} - <span style="font-family:sans-serif;color: #1a237e">{{$product->code}}</span></a>
                                    </h6>
                                    <div class="s-price-box">
                                        @if($product->getDiscountPrice())
                                            <span class="new-price">&euro; {{number_format ($product->getDiscountPrice(),2)}}</span>
                                            <span class="old-price">&euro; {{number_format ($product->price,2)}}</span>
                                        @else
                                            <span class="new-price">&euro; {{number_format ($product->price,2)}}</span>
                                        @endif
                                    </div>

                                    <ul class="action-button">
                                        <li>
                                            {!! Form::open(['method'=>'POST','route'=>['account.wishlist.change']]) !!}
                                            <input type="hidden" name="product_id" value="{{$product->id}}">
                                            <button class="cart_wishlist {{(Auth::check() && Auth::user()->wishlists->contains($product->id))?'active':''}} tippy" title="{{trans('front/products.add_to_wishlist')}}" data-product="{{$product->id}}">
                                                <i class="zmdi zmdi-favorite"></i>
                                            </button>
                                            {!! Form::close() !!}
                                        </li>
                                        <li>
                                            <a class="cart_product tippy" title="{{trans('front/products.add_to_cart')}}" data-toggle="modal" data-target="#productModal" data-product="{{$product->id}}"><i class="zmdi zmdi-shopping-cart-plus"></i></a>
                                        </li>
                                        @if(Auth::check())
                                            @role('superadministrator|administrator|editor')
                                            <li>
                                                <a class="cart_product tippy" title="{{trans('front/products.edit_product')}}" href="{{route('products.edit',$product->id)}}"><i class="zmdi zmdi-edit"></i></a>
                                            </li>
                                            @endrole
                                        @endif
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <!-- product-item end -->
                    @endforeach
                </div>
            </div>
        @endif
    @else
        <div class="shop-option box-shadow mb-30 clearfix">
            <h2 class="mt-10" style="text-align: center">{{trans('front/products.no_results')}}</h2>
        </div>
    @endif
</div>
<!-- Tab Content end -->
<!-- shop-pagination start -->
{{$products->links('vendor.pagination.front')}}