routes/web.php
<?php

// Localisation:
Route::group(['prefix' => LaravelLocalization::setLocale(), 'middleware' => ['localeSessionRedirect', 'localizationRedirect']], function () {

    // Front:
    Route::group(['namespace' => 'Front'], function () {

        // Main:
        Route::get('/', 'FrontController@index')->name('root');
        Route::get('/404-page-not-found', 'FrontController@show404')->name('show404');
        Route::get('/warranty', 'FrontController@warranty')->name('warranty');
        Route::get('/delivery', 'FrontController@delivery')->name('delivery');
        Route::get('/about-us', 'FrontController@about_us')->name('about-us');
        Route::get('/contacts', 'FrontController@contacts')->name('contacts');

        // Catalogue:
        Route::group(['prefix' => 'catalogue'], function () {
            Route::get('/', 'CatalogueController@index')->name('catalogue');
            Route::post('/', 'CatalogueController@ajaxCatalogue')->name('catalogue.ajax');
            Route::get('/product/{id}', 'CatalogueController@product')->name('catalogue.product');
            Route::post('/product/preview', 'CatalogueController@ajaxPreviewProduct')->name('catalogue.product.preview.ajax');
        });

        // Account:
        Route::group(['prefix' => 'account', 'middleware' => 'role:superadministrator|administrator|editor|user', 'middleware_handling' => 'redirect'], function () {

            // Main:
            Route::get('/', 'AccountController@index')->name('account');
            Route::get('/edit', 'AccountController@editAccount')->name('account.edit');
            Route::post('/update', 'AccountController@updateAccount')->name('account.update');

            // Cart:
            Route::get('/cart', 'CartController@index')->name('account.cart');
            Route::post('/cart/quantity', 'CartController@ajaxQuantity')->name('account.cart.quantity.ajax');
            Route::post('/cart/add', 'CartController@add')->name('account.cart.add');
            Route::post('/cart/remove', 'CartController@remove')->name('account.cart.remove');

            // Wishlist:
            Route::get('/wishlist', 'WishlistController@index')->name('account.wishlist');
            Route::post('/wishlist/change', 'WishlistController@change')->name('account.wishlist.change');

            // Review:
            Route::post('/review/publish', 'ReviewController@publish')->name('account.review.publish');

            // Order:
            Route::get('/orders', 'OrderController@index')->name('account.orders');
            Route::get('/orders/{id}', 'OrderController@order')->name('account.order');
            Route::post('/order/cancel', 'OrderController@cancelOrder')->name('account.order.cancel');
            Route::post('/order/complete', 'OrderController@completeOrder')->name('account.order.complete');
            Route::get('/order/checkout', 'OrderController@checkoutOrder')->name('account.order.checkout');
            Route::get('/order/invoice/download/{id}', 'OrderController@downloadInvoice')->name('account.order.invoice.download');
            Route::post('/order/notes', 'OrderController@ajaxOrderNotes')->name('account.order.notes.ajax');
            Route::post('/order/notes/update', 'OrderController@updateOrderNotes')->name('account.order.notes.update');
        });

    });

    // Admin:
    Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => 'role:superadministrator|administrator|editor', 'middleware_handling' => 'redirect', 'middleware_params' => '/home',], function () {

        // Main:
        Route::get('/', 'AdminController@index')->name('admin');
        Route::get('/system/info', 'AdminController@info')->name('system.info');
        Route::get('/system/logs', 'AdminController@logs')->name('system.logs');

        // User:
        Route::resource('/users', 'UserController');
        Route::resource('/permissions', 'PermissionController');
        Route::resource('/roles', 'RoleController');

        // Product:
        Route::resource('/products', 'ProductController');
        Route::post('/products/visible', 'ProductController@productVisibleChange')->name('product.visible');
        Route::post('/products/quantity', 'ProductController@productQuantityChange')->name('product.quantity');

        // Review:
        Route::resource('/reviews', 'ReviewController');
        Route::post('/reviews/visible', 'ReviewController@reviewVisibleChange')->name('review.visible');

        // Order:
        Route::resource('/orders', 'OrderController');
        Route::post('/orders', 'OrderController@changeOrderStatus')->name('order.status.ajax');
        Route::post('/orders/update/tracking-number', 'OrderController@updateTrackingNumber')->name('order.tracking.number.update');
        Route::post('/order/viewed', 'OrderController@orderViewed')->name('order.viewed');

        // Extra:
        Route::resource('/categories', 'CategoryController');
        Route::resource('/subcategories', 'SubcategoryController');
        Route::resource('/materials', 'MaterialController');
        Route::resource('/styles', 'StyleController');
        Route::resource('/tags', 'TagController');
        Route::resource('/sets', 'SetController');
        Route::resource('/sizes', 'SizeController');
        Route::resource('/colors', 'ColorController');
        Route::resource('/gems', 'GemController');
        Route::resource('/photos', 'PhotoController');
        Route::resource('/customers', 'CustomerController');
        Route::resource('/statuses', 'StatusController');
    });

    // Authentication:
    Auth::routes();
    Route::get('/logout', 'Auth\LoginController@logout')->name('logout');
});

resources/views/partials/admin/_photo_gallery.blade.php
<div class="row">
    @if(!$photos->isEmpty())
        @foreach($photos as $photo)
            <div class="col-not-for-mac col-lg-3 col-md-4 col-sm-4">
                <div class="card">
                    <div class="card-header" style="height: auto">
                        <h2 style="font-size: 18px">{{str_limit($photo->name,20)}}</h2>
                        <p style="margin-top: 10px;margin-bottom: 0px;">{{$photo->updated_at ? $photo->updated_at->diffForHumans():'No Date'}}</p>
                    </div>
                    <div class="card-block" style="text-align: center">
                        <a href="{{$photo->getPhotoPath()}}" data-lightbox="gallery">
                            <img src="{{$photo->getPhotoPath()}}" style="width: 100%; border-radius: 0px;height: auto" alt="" class="loading img-thumbnail">
                        </a>
                        <div class="line" style="margin: 19px 0 18px"></div>
                        <div class="row">
                            <div class="col-xs-4" style="margin: 0">
                                <a href="{{route('photos.edit',$photo->id)}}" style="margin-left: 20px;margin-right: 20px; color: #515354;"><i class="fa fa-pencil fa-lg" aria-hidden="true"></i></a>
                            </div>
                            <div class="col-xs-4" style="margin: 0">
                                {!! Form::open(['method'=>'DELETE','route'=>['photos.destroy', $photo->id],'class'=>'delete_photo']) !!}
                                <button type="submit" style="border: none;background: transparent;padding: 0;outline: none;color: red;margin-right: 20px">
                                    <i class="fa fa-trash-o fa-lg" aria-hidden="true" style="color: red"></i>
                                </button>
                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        @endforeach
    @else
        <div class="col-lg-12">
            <div class="card">
                <div class="card-header" style="height: 100px">
                    <h2 style="font-size: 24px;text-align: center;margin: 25px 0">There are no photos yet.</h2>
                </div>
            </div>
        </div>
    @endif
</div>
<div style="margin-bottom: 20px">
    {{$photos->links()}}
</div>