routes/web.php
<?php

// Localisation:
Route::group(['prefix' => LaravelLocalization::setLocale(), 'middleware' => ['localeSessionRedirect', 'localizationRedirect']], function () {

    // Front:
    Route::group(['namespace' => 'Front'], function () {

        // Main:
        Route::get('/', 'FrontController@index')->name('root');
        Route::get('/404-page-not-found', 'FrontController@show404')->name('show404');
        Route::get('/warranty', 'FrontController@warranty')->name('warranty');
        Route::get('/delivery', 'FrontController@delivery')->name('delivery');
        Route::get('/about-us', 'FrontController@about_us')->name('about-us');
        Route::get('/contacts', 'FrontController@contacts')->name('contacts');

        // Catalogue:
        Route::group(['prefix' => 'catalogue'], function () {
            Route::get('/', 'CatalogueController@index')->name('catalogue');
            Route::post('/', 'CatalogueController@ajaxCatalogue')->name('catalogue.ajax');
            Route::get('/product/{id}', 'CatalogueController@product')->name('catalogue.product');
            Route::post('/product/preview', 'CatalogueController@ajaxPreviewProduct')->name('catalogue.product.preview.ajax');
        });

        // Account:
        Route::group(['prefix' => 'account', 'middleware' => 'role:superadministrator|administrator|editor|user', 'middleware_handling' => 'redirect'], function () {

            // Main:
            Route::get('/', 'AccountController@index')->name('account');
            Route::get('/edit', 'AccountController@editAccount')->name('account.edit');
            Route::post('/update', 'AccountController@updateAccount')->name('account.update');

            // Cart:
            Route::get('/cart', 'CartController@index')->name('account.cart');
            Route::post('/cart/quantity', 'CartController@ajaxQuantity')->name('account.cart.quantity.ajax');
            Route::post('/cart/add', 'CartController@add')->name('account.cart.add');
            Route::post('/cart/remove', 'CartController@remove')->name('account.cart.remove');

            // Wishlist:
            Route::get('/wishlist', 'WishlistController@index')->name('account.wishlist');
            Route::post('/wishlist/change', 'WishlistController@change')->name('account.wishlist.change');

            // Review:
            Route::post('/review/publish', 'ReviewController@publish')->name('account.review.publish');

            // Order:
            Route::get('/orders', 'OrderController@index')->name('account.orders');
            Route::get('/orders/{id}', 'OrderController@order')->name('account.order');
            Route::post('/order/cancel', 'OrderController@cancelOrder')->name('account.order.cancel');
            Route::post('/order/complete', 'OrderController@completeOrder')->name('account.order.complete');
            Route::get('/order/checkout', 'OrderController@checkoutOrder')->name('account.order.checkout');
            Route::get('/order/invoice/download/{id}', 'OrderController@downloadInvoice')->name('account.order.invoice.download');
            Route::post('/order/notes', 'OrderController@ajaxOrderNotes')->name('account.order.notes.ajax');
            Route::post('/order/notes/update', 'OrderController@updateOrderNotes')->name('account.order.notes.update');
        });

    });

    // Admin:
    Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => 'role:superadministrator|administrator|editor', 'middleware_handling' => 'redirect', 'middleware_params' => '/home',], function () {

        // Main:
        Route::get('/', 'AdminController@index')->name('admin');
        Route::get('/system/info', 'AdminController@info')->name('system.info');
        Route::get('/system/logs', 'AdminController@logs')->name('system.logs');

        // User:
        Route::resource('/users', 'UserController');
        Route::resource('/permissions', 'PermissionController');
        Route::resource('/roles', 'RoleController');

        // Product:
        Route::resource('/products', 'ProductController');
        Route::post('/products/visible', 'ProductController@productVisibleChange')->name('product.visible');
        Route::post('/products/quantity', 'ProductController@productQuantityChange')->name('product.quantity');

        // Review:
        Route::resource('/reviews', 'ReviewController');
        Route::post('/reviews/visible', 'ReviewController@reviewVisibleChange')->name('review.visible');

        // Order:
        Route::resource('/orders', 'OrderController');
        Route::post('/orders', 'OrderController@changeOrderStatus')->name('order.status.ajax');
        Route::post('/orders/update/tracking-number', 'OrderController@updateTrackingNumber')->name('order.tracking.number.update');
        Route::post('/order/viewed', 'OrderController@orderViewed')->name('order.viewed');

        // Extra:
        Route::resource('/categories', 'CategoryController');
        Route::resource('/subcategories', 'SubcategoryController');
        Route::resource('/materials', 'MaterialController');
        Route::resource('/styles', 'StyleController');
        Route::resource('/tags', 'TagController');
        Route::resource('/sets', 'SetController');
        Route::resource('/sizes', 'SizeController');
        Route::resource('/colors', 'ColorController');
        Route::resource('/gems', 'GemController');
        Route::resource('/photos', 'PhotoController');
        Route::resource('/customers', 'CustomerController');
        Route::resource('/statuses', 'StatusController');
    });

    // Authentication:
    Auth::routes();
    Route::get('/logout', 'Auth\LoginController@logout')->name('logout');
});

resources/views/admin/sizes/edit.blade.php
@extends('layouts.admin')

@section('content')

    {{-- Breadcrumb Section --}}
    <div class="breadcrumb-holder">
        <div class="container-fluid">
            <ul class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{route('admin')}}">Home</a></li>
                <li class="breadcrumb-item"><a href="{{route('sizes.index')}}">Sizes</a></li>
                <li class="breadcrumb-item active">Edit</li>
            </ul>
        </div>
    </div>

    {{-- Tables Section --}}
    <section class="forms">
        <div class="container-fluid">
            <header>
                <h1>SIZE CRUD</h1>
            </header>
            <div class="row">
                <div class="col-md-6">
                    <div class="card">
                        {!! Form::model($size,['method'=>'PATCH','route'=>['sizes.update',$size->id],'class'=>'form-horizontal']) !!}
                        <div class="card-header">
                            <h1>Size Details</h1>
                        </div>

                        <div class="card-block">
                            <div class="form-group row" style="margin: 0">
                                <label class="col-sm-3">Value</label>
                                <div class="col-sm-9">
                                    <input name="value" type="number" step=0.5 placeholder="Value" value="{{$size->value}}" class="form-control form-control-success">
                                </div>
                            </div>
                            <div class="form-group row" style="margin-top: 30px;margin-left: 0px">
                                <div class="col-sm-10">
                                    <input type="submit" value="Update Size" class="btn btn-outline-primary">
                                </div>
                            </div>
                            {!! Form::close() !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

@endsection

resources/views/admin/sizes/index.blade.php
@extends('layouts.admin')

@section('title',"Manage | Categories")

@section('styles')

    <style>
        .sweet-alert button{
            margin: 26px 5px 15px 5px !important;
        }
    </style>

    <style>
        .counter {
            font-size: 17px;
            padding: 8px 10px;
            margin-bottom: 0;
            min-width: 250px;
            float: right;
            font-weight: initial;
            background: #fff;
            box-shadow: 1px 1px 2px rgba(0, 0, 0, 0.3);
            text-align: center
        }
    </style>

@endsection

@section('content')

    {{-- Breadcrumb Section --}}
    <div class="breadcrumb-holder">
        <div class="container-fluid">
            <ul class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{route('admin')}}">Home</a></li>
                <li class="breadcrumb-item active">Sizes</li>
            </ul>
        </div>
    </div>

    {{-- Tables Section --}}
    <section class="charts">
        <div class="container-fluid">
            <header>
                <h1 style="float:left">SIZE CRUD</h1>
                <h2 class="counter">Size Number :
                    <span style="font-size: 17px;color: #0275d8;">{{\App\Size::all()->count()}}</span>
                </h2>
            </header>
            <div class="row" style="margin-top: 30px">
                <div class="col-lg-7">
                    <div class="card">
                        <div class="card-header" style="height: auto">
                            <h1 class="float-left">All Sizes</h1>
                        </div>
                        <div class="card-block">
                            <table class="table table-lg table-bordered">
                                <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Value</th>
                                    <th>Updated</th>
                                    <th style="width: 130px">Actions</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($sizes as $size)
                                    <tr>
                                        <th>{{$size->id}}</th>
                                        <td>{{$size->value}}</td>
                                        <td>{{$size->updated_at ? $size->updated_at->diffForHumans():'No Date'}}</td>
                                        <td>
                                            <div class="row">
                                                <div class="col-xs-4" style="margin: 0">
                                                    <a href="{{route('sizes.show',$size->id)}}" style="margin-left: 20px;margin-right: 20px"><i class="fa fa-eye fa-lg" aria-hidden="true"></i></a>
                                                </div>
                                                <div class="col-xs-4" style="margin: 0">
                                                    <a href="{{route('sizes.edit',$size->id)}}" style="margin-right: 20px"><i class="fa fa-pencil fa-lg" aria-hidden="true"></i></a>
                                                </div>
                                                <div class="col-xs-4" style="margin: 0">
                                                    {!! Form::open(['method'=>'DELETE','route'=>['sizes.destroy', $size->id],'class'=>'delete_size']) !!}
                                                    <button type="submit" style="border: none;background: transparent;padding: 0">
                                                        <i class="fa fa-trash-o fa-lg" aria-hidden="true" style="color: red"></i>
                                                    </button>
                                                    {!! Form::close() !!}
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="col-lg-5" style="max-height: 250px">
                    <div class="card">
                        {!! Form::open(['method'=>'POST','route'=>'sizes.store','class'=>'form-horizontal']) !!}
                        <div class="card-header">
                            <h1>New Size</h1>
                        </div>
                        <div class="card-block">
                            <div class="form-group row" style="margin: 0">
                                <label class="col-sm-5">Size Value</label>
                                <div class="col-sm-7">
                                    <input name="value" type="number" step=0.5 placeholder="enter value..." value="{{old('value')}}" class="form-control form-control-success">
                                </div>
                            </div>
                            <div class="form-group row" style="margin-top: 30px;margin-left: 0px">
                                <div class="col-sm-10">
                                    <input type="submit" value="Add Size" class="btn btn-outline-primary">
                                </div>
                            </div>
                            {!! Form::close() !!}
                        </div>
                    </div>
                </div>
            </div>
            <div style="margin-bottom: 20px">
                {{$sizes->links()}}
            </div>
        </div>
    </section>

@endsection

@section('scripts')

    <script>
        $(".delete_size").submit(function (e) {
            var form = this;
            e.preventDefault();
            swal({
                    title: "Are you sure?",
                    text: "You will not be able to recover this size!",
                    type: "warning",
                    showCancelButton: true,
                    confirmButtonColor: '#DD6B55',
                    confirmButtonText: 'Yes, I am sure!',
                    cancelButtonText: "No, cancel it!",
                    closeOnConfirm: false,
                    closeOnCancel: false
                },
                function (isConfirm) {
                    if (isConfirm) {
                        swal({
                            title: 'Size Deleted!',
                            text: 'Size is successfully deleted!',
                            type: 'success'
                        }, function () {
                            form.submit();
                        });

                    } else {
                        swal("Cancelled", "Your size is safe", "error");
                    }
                }
            );
        });
    </script>

@endsection

resources/views/admin/sizes/show.blade.php
@extends('layouts.admin')

@section('content')

    {{-- Breadcrumb Section --}}
    <div class="breadcrumb-holder">
        <div class="container-fluid">
            <ul class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{route('admin')}}">Home</a></li>
                <li class="breadcrumb-item"><a href="{{route('sizes.index')}}">Sizes</a></li>
                <li class="breadcrumb-item active">Show</li>
            </ul>
        </div>
    </div>

    {{-- Tables Section --}}
    <section class="charts">
        <div class="container-fluid">
            <header>
                <h1>SIZE CRUD</h1>
            </header>
            <div class="row">
                <div class="col-lg-9">
                    <div class="card">
                        <div class="card-header" style="height: auto">
                            <h1 class="float-left">Size Details</h1>
                            <a href="{{route('sizes.edit',$size->id)}}" class="btn btn-outline-primary float-right">Edit Size</a>
                        </div>
                        <div class="card-block">
                            <div class="form-group row">
                                <label class="col-sm-4">Value</label>
                                <h2 class="col-sm-8">{{$size->value}}</h2>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-9">
                    <div class="card">
                        <div class="card-header">
                            <h1>Products:</h1>
                        </div>
                        <div class="card-block" style="margin-left: 20px">
                            <ul>
                                @foreach($size->products as $product)
                                    <li>{{$product->name}}</li>
                                @endforeach
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

@endsection